version: "3.9"

services:
  workspace:
    container_name: spring-boot-ddd
    build:
      context: ./
    tty: true
    volumes:
      - ../:/home/kyoto_kanko/workspace:cached
    networks:
      - backend-network
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge
volumes:
  mysql-data:
